/**
 * Harbors for each level, frozen: finding one takes a search (`makeHarbor`), which is too slow to run while a child
 * waits. `logic.test.ts` checks that every one is well formed, can be finished, and needs a number of slides within
 * its plan's range at the fewest. To add more, call `makeHarbor(PLANS[level - 1], new Rng(seed))` for new seeds and
 * paste what `render` returns.
 */
export const HARBORS: Record<number, string[][]> = {
  1: [
    ['b...', 'b..c', 'ff.c', 'aa..'],
    ['.a..', '.a.c', 'ff.c', '.bbb'],
    ['....', '.bb.', '.ffa', '...a'],
    ['...a', '.ffa', '..b.', 'ccb.'],
    ['aa..', 'ffc.', '..cb', '...b'],
    ['...b', '.ffb', '..a.', '..a.'],
    ['..a.', '..a.', '.ffb', '...b'],
    ['....', 'aa..', 'ffb.', '..b.'],
    ['..aa', '....', 'cffb', 'c..b'],
    ['....', '.ffc', '.bbc', '.aa.'],
    ['...b', 'ff.b', 'a...', 'a...'],
    ['b...', 'b..a', 'ff.a', '....'],
    ['.cc.', '....', 'ff.a', 'bb.a'],
    ['...b', 'ccab', 'ffa.', '....'],
  ],
  2: [
    ['aacb', 'ffcb', '....', '.dd.'],
    ['c..b', 'cffb', 'c.dd', '..aa'],
    ['..aa', '..c.', 'ffcb', '...b'],
    ['..bb', '....', 'ffac', '..ac'],
    ['...c', '.ffc', '..aa', '.bbb'],
    ['.bb.', '..ca', 'ffca', '....'],
    ['.aaa', '..bb', '.ffc', '...c'],
    ['....', '..cc', 'ffba', '..ba'],
    ['.bb.', '..ac', 'ffac', '....'],
    ['..bb', '.aaa', '.ffc', '...c'],
    ['....', '.cca', 'ffba', '..b.'],
    ['b...', 'baaa', 'ff.c', '...c'],
    ['..b.', 'ffba', '...a', '.cc.'],
    ['..bb', '..cc', '.ffa', '...a'],
  ],
  3: [
    ['.....', '.ffad', '...ad', 'bccc.', 'b..ee'],
    ['.dd..', '...ec', 'ffaec', '..a..', '.bb..'],
    ['...bb', 'cc.a.', '.dda.', 'ffea.', '..e..'],
    ['...c.', 'ff.c.', 'e..bb', 'eddd.', '.aa..'],
    ['ggbbb', '...dc', '.ffdc', '..eee', '..aa.'],
    ['....b', 'ffe.b', '..egg', '...dd', 'aacc.'],
    ['...d.', 'ffade', 'ccade', '...bb', '.....'],
    ['..ddc', 'ff.ac', 'e..a.', 'e..a.', 'ebbb.'],
    ['..ddb', 'ff..b', 'cgg..', 'caaee', 'c....'],
    ['...c.', 'ff.ce', 'a..ce', 'ab...', '.bdd.'],
    ['accdd', 'a...e', 'b...e', 'bff.e', '.....'],
    ['.gg..', 'ff.d.', 'bb.d.', 'aeee.', 'a..cc'],
    ['d....', 'dbbb.', '...c.', 'ff.ca', '....a'],
    ['...dc', 'bffdc', 'baaac', '.....', '.....'],
  ],
  4: [
    ['...hh', '.ff.a', 'eee.a', 'gcbbb', 'gcddd'],
    ['....a', '.ffda', '...da', '..cbb', '..cee'],
    ['..g..', 'ffg.a', 'c.bba', 'c..ea', 'ddde.'],
    ['hddda', 'h...a', 'ffg..', 'e.gb.', 'eccb.'],
    ['eaaa.', 'e.bbb', 'ddd.h', '.ffch', 'gg.c.'],
    ['..d..', '..dbb', 'aacce', '.ff.e', '..ggg'],
    ['.dhbb', '.dh..', '..hge', '.ffge', 'ccaae'],
    ['..ccc', 'b....', 'baagg', 'ffe.d', '..e.d'],
    ['..a.g', '..a.g', '.ff.d', '.ec.d', '.ecbb'],
    ['...db', '.ffdb', '..cd.', '..caa', '...ee'],
    ['.cbee', '.cb.a', '..bda', '.ffda', '.....'],
    ['.....', '.ffce', '..bce', '.dbc.', '.dbaa'],
    ['e.gbb', 'e.gh.', '.ffhc', '..adc', '..ad.'],
    ['.hggg', '.h.aa', 'ffd..', '.ed.b', '.eccb'],
  ],
  5: [
    ['....ig', '.ffaig', '...ai.', '..dhhb', 'c.d..b', 'c..eee'],
    ['..g..h', 'ffg..h', 'e.gd..', 'e..d..', '.aaa.c', '...bbc'],
    ['...aa.', 'dcc...', 'd.....', 'ffhge.', '.bhge.', '.bh.e.'],
    ['....gh', '....gh', 'ffc.g.', 'b.ceee', 'b.....', 'baa.dd'],
    ['..d.ee', 'ccdbi.', 'hffbi.', 'h.ggaa', 'h.....', '......'],
    ['...db.', '...dbc', '.gggbc', 'aae..c', 'ffe...', '....hh'],
    ['....bb', '.cc.d.', '.ff.d.', 'eee.d.', '..g...', '..gaa.'],
    ['eee..b', '..a.hb', 'ffa.h.', 'c..d..', 'cggdii', '......'],
    ['......', '.cc.e.', '....ea', '..g..a', 'ffghdb', '..ghdb'],
    ['...ab.', 'ff.ab.', '.ddee.', 'cc..hh', '...ggg', '......'],
    ['eeehhg', '..ab.g', 'ffabdc', '..a.dc', '.....c', '...iii'],
    ['.....a', '.cccha', 'ee..h.', 'ffd...', '..dbgg', '..db..'],
    ['ddhh..', '..a.i.', 'ffaci.', '..ecig', '..ebbg', '.....g'],
    ['..g...', 'ffga.b', '...a.b', '.eee.b', '.ddd..', '.cc...'],
  ],
  6: [
    ['..h.e.', 'ffh.e.', '....bb', 'gggd.a', 'ciid.a', 'c..d.a'],
    ['.dd.ii', 'bb..e.', 'ghhhe.', 'gcca..', 'ffja..', 'kkj...'],
    ['.ii...', 'gddd.e', 'g..aae', 'g.hb.e', 'ffhb..', '..hcc.'],
    ['....d.', '.cc.da', '.ffgda', 'hhhg..', '..bjii', '..bjee'],
    ['hh.ii.', 'c.....', 'cffkba', '..dkba', 'g.djba', 'g.djee'],
    ['b..c.d', 'beec.d', '..hg.d', 'ffhg..', '..aaa.', '...ii.'],
    ['e.ii..', 'e..add', 'ff.a..', '.ggabk', '.jhhbk', '.jccc.'],
    ['a.ddcc', 'a...ee', 'a..hkk', '..bhij', 'ffbhij', '..gggj'],
    ['..a...', '..ag..', 'cc.gi.', 'ffegib', '.je.hb', '.jddh.'],
    ['kkk.a.', 'ffb.ae', '..b..e', 'ichhhe', 'icddjj', '...gg.'],
    ['g...b.', 'gff.b.', 'hhc...', '..caii', '...a..', 'dddaee'],
    ['....hh', 'dbb.g.', 'd.e.gc', 'ffe.gc', '..e...', '..aaa.'],
    ['hgg.ii', 'hjj.b.', 'hff.b.', 'aaa.b.', '.c....', '.ceedd'],
    ['geii..', 'geddda', 'hhc..a', '..c.ba', '.ff.b.', '....b.'],
  ],
};
