/**
 * Every line the game speaks, keyed by id. Arrays are variations picked at random.
 * `{name}` is the child's name; other `{words}` are filled in by the caller.
 * This is also the script for recording parents' voices later.
 */
export const SCRIPT = {
  'start.hi': ['Hi, {name}!', 'Hello, {name}!', 'Yay, {name} is here!'],
  'hub.pick': ['What should we play?', 'Pick a game!', "Let's play!"],
  'hub.again': ['What next?', 'Ooh, what now?'],
  'map.pick': ['Where shall we play, {pet}? Tap a place on our island!'],
  'map.birthday': ['Happy birthday, {pet}! We are growing up together. Let us walk up the island!'],
  'place.lap': ['Puddle Lagoon!'],
  'place.toddler': ['Daisy Meadow!'],
  'place.preschool': ['Bumpy Hills!'],
  'place.prek': ['Starry Peak!'],
  'place.school': ['Wonder Woods!'],
  'place.subjects': ['Pick a picture to find games! Swipe or tap an arrow for more.'],
  'subject.senses': ['Bubble Beach! Popping, bouncing, and splashing.'],
  'subject.music': ['Music Mountain! Songs and sounds.'],
  'subject.art': ['Treehouse! Pictures and making.'],
  'subject.animals': ['Barnyard! Animal friends.'],
  'subject.numbers': ['Counting Cove! Counting and sharing.'],
  'subject.everyday': ['Cozy Village! Helping and pretend play.'],
  'subject.shapes': ['Rainbow Meadow! Colors and shapes.'],
  'subject.puzzles': ['Puzzle Peaks! Patterns and puzzles.'],
  'subject.stories': ['Story Grove! Letters and stories.'],
  'subject.science': ['Tinker Lab! Try things and discover.'],
  'place.more': ['Swipe to see more games!'],
  'hatch.tap': ['Someone is inside! Tap the egg!'],
  'hatch.color': ['Hello, little friend! Pick a color for your pet, then tap the green arrow.'],
  'hatch.name': ['What shall we call our friend? Tap a name to hear it, then tap the green arrow.'],
  'hatch.try-name': ['{pet}!'],
  'hatch.hello': ['Hello, {pet}! Let us explore our island!'],
  'stickers.place': ['Drag a sticker onto the picture! Put it back in the tray to move it away.'],
  'stickers.meadow': ['A meadow!'],
  'stickers.beach': ['The beach!'],
  'stickers.farm': ['A farm!'],
  'stickers.sea': ['Under the sea!'],
  'stickers.space': ['Outer space!'],
  'poke.pip': ['Hee hee!', 'That tickles!', 'Boop!', 'Hi!'],

  'game.stamp-studio': ['Stamp studio!'],
  'stamp.stars': ['Tap the paper to stamp stars! The green arrow finishes your picture.'],
  'stamp.friends': ['Choose a cat or a fish, then tap the paper! The green arrow finishes your picture.'],
  'stamp.picture': ['Choose a stamp and a color, then tap the paper. Drag your stamps to arrange them. Finish with the green arrow.'],
  'stamp.sizes': ['Make a picture! Touch a stamp to choose it, then turn it or make it big or small.'],
  'stamp.garden': ['What grows in your imaginary garden? Make any picture you like! Tell me about it, then tap the green arrow.'],
  'stamp.story': ['Make a picture of two friends on an adventure. Your story can be anything! Finish with the green arrow.'],
  'stamp.kind': ['{kind}! Tap the paper to stamp it.'],
  'stamp.full': ['Your paper has lots of stamps! Move one, undo a stamp with the back arrow, or finish with the green arrow.'],
  'stamp.done': ['You made your own picture!'],
  'game.pet-kitchen': ['Pet kitchen!'],
  'kitchen.cut': ['Cut our sandwiches into equal pieces for {n} friends. Tap a cutting picture.'],
  'kitchen.share': ['Share the pieces with {n} friends. Move pieces between plates until everyone has the same. Tap the green arrow to serve.'],
  'kitchen.fair': ['Does everyone have the same amount? Move a piece to a plate with less.'],
  'kitchen.recut': ['We need more equal pieces. Tap the round arrow to put the sandwich together, then cut it into quarters.'],
  'kitchen.double': ['Let us make twice this recipe! Put two fruits in for each fruit on the card. Tap the green arrow to serve.'],
  'kitchen.double-hint': ['Two for each one on the card! Count each kind. Use the back arrow to take the last fruit out.'],
  'kitchen.undo': ['The bowl has lots of fruit. Use the back arrow to take the last one out.'],
  'kitchen.done': ['A meal to share! Thank you, chef!'],
  'game.tangram-town': ['Tangram town!'],
  'tangram.fit': ['Build a {picture}! Drag each shape onto the shadow.'],
  'tangram.turn': ['Build a {picture}! Choose a shape, then tap the round arrow to turn it. The yellow button helps.'],
  'tangram.try': ['Try another shape or turn. Look at the edges of the shadow.'],
  'tangram.help': ['I turned this shape for you. Move it onto the glowing place.'],
  'tangram.done': ['Your {picture} is ready!'],
  'game.rhythm-neighbors': ['Rhythm neighbors!'],
  'neighbors.free': ['Tap the woodpecker to hear a call and an answer. Tap a frog to join in! The green arrow finishes our song.'],
  'neighbors.turns': ['The bird calls, then the frogs answer. Listen, then play the frog pictures from left to right. Tap the green arrow when ready.'],
  'neighbors.rhythm': ['Listen to the bird and the frog reply. Now play the frog part, with short and long gaps. Tap the green arrow when ready.'],
  'neighbors.your-turn': ['Your turn! Play the frog reply.'],
  'neighbors.again': ['Let us listen to that reply again. Follow the frog pictures.'],
  'neighbors.help': ['Follow the glowing frog, at your own pace. Then tap the green arrow.'],
  'neighbors.done': ['We made a song together!'],
  'seesaw.twins': ['Two boxes weigh the same. Balance both boxes with blocks, then find how heavy one box is.'],
  'seesaw.each': ['Both boxes weigh {n} blocks together. They weigh the same. How many blocks heavy is one box?'],
  'seesaw.twins-hint': ['Share the {n} blocks into two equal groups. Each box weighs {each} blocks. Count each group with me.'],
  'tricks.parcel': ['Make the parcel fit! Tap the round arrow to turn it, then move it onto the mailbox shadow.'],
  'tricks.parcel-hint': ['Look at the long edges and corners. Turn the parcel, then try it in the shadow.'],
  'tricks.places': ['A bowl for everyone! Move a bowl to each friend who needs one.'],
  'tricks.places-hint': ['Someone still needs a bowl! Find an empty place.'],
  'tricks.berries': ['Make {n} berries! Some are here already. Add berries, then tap the yellow arrow.'],
  'tricks.berries-hint': ['Count every berry, including the ones already here. We need {n}. The back arrow takes one away.'],
  'tricks.encore-yes': ['Ta-da! Tap the green arrow when you are ready.'],
  'game.bubble-pop': ['Bubbles!'],
  'game.jelly-drums': ['Jelly drums!'],
  'game.rainbow-fingers': ["Let's paint!"],
  'game.stickers': ['Your stickers!'],
  'game.peekaboo-barn': ['Peekaboo!'],
  'game.duck-pond': ['Duck pond!'],
  'game.shape-sorter': ['Shapes!'],
  'game.color-garden': ['The color garden!'],
  'game.splish-splash': ['Bath time!'],
  'game.pattern-train': ['Pattern Train!'],
  'game.memory-match': ['Memory Match!'],
  'game.duckling-parade': ['Duckling parade!'],
  'game.scoop-shop': ['Scoop shop!'],
  'game.roundup': ['Roundup!'],
  'game.bouncy-launch': ['Bouncy launch!'],
  'game.word-monsters': ['Word monsters!'],
  'game.peg-garden': ['Peg garden!'],
  'game.fluffy-salon': ['Fluffy salon!'],
  'game.sound-garden': ['Sound garden!'],
  'game.little-helpers': ['Little helpers!'],
  'game.egg-catch': ['Egg catch!'],
  'game.mail-carrier': ['Mail carrier!'],
  'game.photo-safari': ['Photo safari!'],
  'game.peekaround-island': ['Peekaround Island!'],
  'game.light-lab': ['Light lab!'],
  'game.penguin-slide': ['Penguin slide!'],
  'game.secret-code': ['Secret code!'],
  'game.frog-hop': ['Frog hop!'],
  'game.market-stall': ['Market stall!'],
  'game.garden-grow': ['Garden grow!'],
  'game.clock-tower': ['Clock tower!'],
  'game.pixel-pictures': ['Pixel pictures!'],
  'game.goodnight-room': ['Goodnight room!'],
  'game.animal-snack': ['Animal snack!'],
  'game.beat-builder': ['Beat builder!'],
  'game.rhyme-time': ['Rhyme time!'],
  'game.stop-and-go': ['Stop and go!'],
  'game.ramp-race': ['Ramp race!'],
  'game.critter-sort': ['Critter sort!'],
  'game.treasure-map': ['Treasure map!'],
  'game.opposites': ['Opposites!'],
  'game.picture-graph': ['Picture graph!'],
  'game.inchworm': ['Inchworm measure!'],
  'game.bounce-back': ['Bounce back!'],
  'game.dot-link': ['Dot link!'],
  'dots.tap': ['Tap the dots to pop them!'],
  'dots.pair': ['Draw a line between two dots of the same color!'],
  'dots.color': ['Pop {n} {color} dots!'],
  'dots.chain': ['Make a chain of {n} dots!'],
  'dots.square': ['Make a square! Go all the way around four dots of one color.'],
  'dots.notthat': ["That's {wrong}! Pop the {color} dots."],
  'dots.longer': ['Longer! Try {n} in a row.'],
  'dots.around': ['Go all the way around to make a square!'],
  'dots.done': ['Pop pop hooray!'],
  'game.seesaw-balance': ['Seesaw!'],
  'seesaw.up': ['Make the {animal} go up! Put a friend on the other side.'],
  'seesaw.heavy': ['Make the {animal} go up! Who is heavy enough?'],
  'seesaw.other': ['Oops, the same side! Put a friend on the other side.'],
  'seesaw.light': ['Too light! The {animal} is still down. Try a bigger friend.'],
  'seesaw.wee': ['Wheee! Up goes the {animal}!', 'Up, up, up!'],
  'seesaw.level': ['Make the seesaw level! Put blocks on the other side.'],
  'seesaw.this-side': ['Put them on the other side!'],
  'seesaw.too-many': ['Too heavy! That side went down. Take one off.'],
  'seesaw.balanced': ['Level! Just the same!', 'Balanced!'],
  'seesaw.heaviest': ['Which present is the heaviest? Try them on the seesaw, then put the heaviest one in the wagon!'],
  'seesaw.not-heaviest': ['Hmm, another present is heavier. Try them on the seesaw!'],
  'seesaw.heaviest-yes': ['Yes! That is the heaviest present!'],
  'seesaw.parts': ['This side weighs {n}. Make the other side weigh {n} too!'],
  'seesaw.mystery': ['How heavy is the mystery box? Add blocks until the seesaw is level!'],
  'seesaw.how-many': ['Level! How many blocks heavy is the box?'],
  'seesaw.box': ['The box weighs {n} blocks!'],
  'seesaw.count-again': ['Let us count the blocks together.'],
  'seesaw.done': ['What a great balancer!'],
  'game.teddy-doctor': ['Teddy doctor!'],
  'doctor.play': ['Oh no, boo-boos! Tap them to put on bandages.'],
  'doctor.part': ['Ouch! Please put a bandage on my {part}.'],
  'doctor.notthat': ['That is my {touched}. Where is my {part}?'],
  'doctor.scrape': ['Ouch! I scraped my {part}.'],
  'doctor.bump': ['Ow! I bumped my head.'],
  'doctor.sniffles': ['Achoo! My nose is drippy.'],
  'doctor.tummy': ['Ooh, my tummy hurts.'],
  'doctor.cold': ['Brrr! My feet are so cold.'],
  'doctor.what': ['What will help?'],
  'doctor.wrong-tool': ['Hmm, that will not help. What else could we try?'],
  'doctor.not-there': ['Not there! Where does it hurt?'],
  'doctor.card': ['Time for a check-up! Do the steps on the card, one at a time.'],
  'doctor.told': ['Time for a check-up! Please {a}, then {b}, then {c}.'],
  'doctor.first': ['First, {step}!'],
  'doctor.heart': ['Thump thump! A strong heart.'],
  'doctor.temp': ['Beep! Just right.'],
  'doctor.ears': ['Nice clean ears!'],
  'doctor.better': ['All better! Thank you, doctor!', 'I feel much better!'],
  'doctor.done': ['Everyone feels better. What a kind doctor!'],
  'game.bumper-garden': ['Bumper garden!'],
  'bumper.spring': ['Tap to send the ladybug up! Watch the flowers bloom.'],
  'bumper.bloom': ['Tap this side or that side to flip the ladybug back up. Make every flower bloom!'],
  'bumper.color': ['Bloom the {color} flowers!'],
  'bumper.order': ['Bump the flowers in order. Find {n}!'],
  'bumper.next': ['Now {n}!'],
  'bumper.again-color': ['Almost! Find the {color} flowers.'],
  'bumper.again-order': ['Where is {n}? Flip it up again!'],
  'bumper.hint': ['Watch! The ladybug will fly toward the glowing flower.'],
  'bumper.done': ['The whole garden is blooming!'],
  'game.quick-tricks': ['Quick tricks!'],
  'tricks.start': ['Welcome to the show! Three quick tricks.'],
  'tricks.umbrella': ['Rain! Keep Bunny dry. Hold the leaf up high!'],
  'tricks.umbrella-two': ['Rain! Keep Bunny and Duck dry. Which leaf can cover them both?'],
  'tricks.above': ['Up high! The leaf goes above Bunny.'],
  'tricks.still-wet': ['Oh! Someone is still wet. Try the bigger leaf!'],
  'tricks.dry': ['Nice and dry! And look at the little flower!'],
  'tricks.socks': ['The sock monster lost a sock! Find its partner.'],
  'tricks.socks-both': ['Find the partner sock: the same color and the same pattern!'],
  'tricks.not-color': ['Not that one! Look at the color.'],
  'tricks.not-pattern': ['Same color, but look at the pattern!'],
  'tricks.partner': ['A pair! What silly ears!'],
  'tricks.bridge': ['Beetle wants to cross. Stretch the bridge all the way over!'],
  'tricks.bridge-choose': ['Beetle wants to cross. Which plank is long enough?'],
  'tricks.too-short': ['Not far enough! Stretch it all the way to the other side.'],
  'tricks.too-short-choose': ['Too short! Try a longer plank.'],
  'tricks.across': ['Across! The bridge takes a bow.'],
  'tricks.next': ['Tap the arrow for the next trick!'],
  'tricks.done': ['What a show! Everybody bow!'],
  'bounce.solo': ['Slide your paddle and bounce the ball back to {pet}!'],
  'bounce.together': ['Play together! One paddle each. Keep it bouncing!'],
  'bounce.stars': ['Bounce the ball through the stars!'],
  'bounce.count': ['Let us bounce it {n} times! Count with me.'],
  'bounce.whoops': ['Whoops! Here it comes again.', 'Oopsie! Again!'],
  'bounce.done': ['What a great rally!', 'Boing boing hooray!'],
  'worm.lay': ['How long is the {what}? Drag inchworms onto it, end to end, from one end to the other!'],
  'worm.again': ['Now measure the {what}!'],
  'worm.compare': ['Measure the {a} and the {b} with inchworms. Which is longer?'],
  'worm.ruler': ['How long is the {what}? Count the spaces on the ruler.'],
  'worm.rulerstart': ['How long is the {what}? Careful: it does not start at 0!'],
  'worm.toomany': ['That one would hang off the end of the {what}!'],
  'worm.long': ['The {what} is {n} long!'],
  'worm.howlong': ['How many inchworms long is the {what}?'],
  'worm.howmuch': ['How many inchworms longer is the {a} than the {b}?'],
  'worm.countagain': ['Count the inchworms again.'],
  'worm.spaces': ['Count the spaces under it, one by one.'],
  'worm.fromzero': ['That is where it ends, but it did not start at 0. Count the spaces it covers.'],
  'worm.yay': ['Right!', 'Measured!'],
  'worm.done': ['What a measurer!'],
  'graph.build': ['Count the critters in the meadow. Tap above a bar to add a block for each one. Then tap the green check!'],
  'graph.recount': ['Count the {kind} again.'],
  'graph.built': ['What a graph!', 'The graph matches the meadow!'],
  'graph.most': ['Which critter has the most? Tap its bar.'],
  'graph.fewest': ['Which has the fewest? Tap its bar.'],
  'graph.more': ['How many more {a} than {b}?'],
  'graph.total': ['How many critters in all?'],
  'graph.same': ['Which two bars are the same? Tap them both.'],
  'graph.look': ['Look at the bars again.'],
  'graph.yay': ['Right!', 'You read the graph!'],
  'graph.done': ['Super graphing!'],
  'opp.switch': ['Tap the picture and it turns into its opposite!'],
  'opp.word': ['{word}!'],
  'opp.find': ['Which one is {word}? Tap it!'],
  'opp.opposite': ['This one is {word}. Find the opposite!'],
  'opp.pairs': ['Find the opposites! Tap one, then its opposite.'],
  'opp.notfind': ['That one is {what}. Which one is {word}?'],
  'opp.notopp': ['{what} is not the opposite of {word}.'],
  'opp.notpair': ['{a} and {b} are not opposites.'],
  'opp.pair': ['{a} and {b}!'],
  'opp.yay': ['Yes!', 'You got it!', 'That is right!'],
  'opp.done': ['Big hooray, not a small one!'],
  'map.pictures': ['Dig where the {pic} row meets the {color} column!'],
  'map.letters': ['Dig at {sq}! Find column {col}, then go up to row {row}.'],
  'map.place': ['Put the {thing} at {sq}!'],
  'map.steps': ['Start where the pet is. Go {dirs}. Where do you end up? Tap that square!'],
  'map.col': ['Right column! Now look up and down it for the row.'],
  'map.row': ['Right row! Now look along it for the column.'],
  'map.neither': ['Not there. Find the column first, then the row.'],
  'map.stepswrong': ['Count the steps again: {dirs}.'],
  'map.hint': ['Look where the glowing column and row cross.'],
  'map.found': ['Treasure!', 'You found it!', 'X marks the spot!'],
  'map.placed': ['There it is!', 'Right on the map!'],
  'map.done': ['What a treasure hunter!'],
  'ramp.explore': ['Tap the ramp to make it taller or shorter. Then press go and watch the car roll!'],
  'ramp.height': ['Make the car stop on the star! Tap the ramp to change how tall it is, then press go.'],
  'ramp.both': ['Now the floor changes too! Tap the floor for carpet, wood or ice. Can you stop on the star?'],
  'ramp.fair.floor': ['Which floor lets the car roll farther? Make it a fair test: change only the floor, and keep both ramps the same height.'],
  'ramp.fair.height': ['Does a taller ramp make the car go farther? Make it a fair test: change only the ramp, and keep both floors the same.'],
  'ramp.went': ['{n} marks!', 'It rolled {n} marks!'],
  'ramp.woodonly': ['This floor is wood. Change the ramp instead!'],
  'ramp.short': ['Too short! A taller ramp makes it go farther.'],
  'ramp.long': ['Too far! Try a shorter ramp.'],
  'ramp.short2': ['Too short! A taller ramp or a more slippery floor goes farther.'],
  'ramp.long2': ['Too far! A shorter ramp or a rougher floor stops sooner.'],
  'ramp.hint': ['Try the ramp and floor that glow.'],
  'ramp.yay': ['Right on the star!', 'Perfect stop!'],
  'ramp.same.floor': ['Both lanes are the same! Change the floor on one of them.'],
  'ramp.same.height': ['Both lanes are the same! Change the ramp on one of them.'],
  'ramp.unfair.floor': ['That is not a fair test: the ramps are different too. Change only the floor.'],
  'ramp.unfair.height': ['That is not a fair test: the floors are different too. Change only the ramp.'],
  'ramp.fairyay': ['A fair test! The {what} went farther.'],
  'ramp.done': ['What a scientist! You tested it fairly.'],
  'sort.one': ['Put every critter {a} in the hoop!'],
  'sort.two': ['One hoop is for critters {a}, the other is for critters {b}. Some critters do not go in either!'],
  'sort.venn': ['One hoop is for critters {a}, the other for critters {b}. Critters that are both go in the middle!'],
  'sort.guess': ['These critters are already sorted. What is the rule for the hoop? Tap the picture!'],
  'sort.isnot': ['The {who} is not {rule}.'],
  'sort.both': ['The {who} is {a} and {b}, so it goes in the middle, in both hoops!'],
  'sort.notguess.out': ['But the {who} is {rule}, and it is not in the hoop.'],
  'sort.notguess.in': ['But the {who} is in the hoop, and it is not {rule}.'],
  'sort.yay': ['All sorted!', 'Every critter is in the right place!'],
  'sort.guessyay': ['Yes! The rule is: {rule}!'],
  'sort.done': ['Super sorting!'],
  'go.toy': ['Tap the traffic light! Green means go, red means stop.'],
  'go.send': ['When the light is green, tap the car to make it go. Red means wait!'],
  'go.walk': ['Red light, green light! Tap the feet to walk on green. On red, freeze!'],
  'go.cross': ['You are the traffic helper! Tap a light to turn it green and let its cars go. Only one road can be green at a time.'],
  'go.zoom': ['Zoom!', 'Beep beep, off it goes!', 'Vroom!'],
  'go.yellow': ['Yellow means slow down. Wait for green!'],
  'go.red': ['Red means stop! Wait for green.'],
  'go.both': ['Oops! Both roads are green. Make one of them red.'],
  'go.turn': ['That road is empty now. Give the other road a turn: red here, green there!'],
  'go.is.red': ['Red! Stop!'],
  'go.is.yellow': ['Yellow! Slow down!'],
  'go.is.green': ['Green! Go!'],
  'go.done': ['Great driving! Everyone got there safely.'],
  'rhyme.match': ['{prompt}! Which one rhymes with {prompt}? {list}?'],
  'rhyme.pair': ['Find the two that rhyme: {list}.'],
  'rhyme.odd': ['Which one does not rhyme? {list}.'],
  'rhyme.word': ['{word}'],
  'rhyme.no': ['{prompt}, {word}. Those do not rhyme. Listen to the ends of the words.'],
  'rhyme.nopair': ['{a}, {b}. Those do not rhyme. Try another two.'],
  'rhyme.noodd': ['{word} rhymes with {other}! Which one is left out?'],
  'rhyme.yes': ['{a}, {b}! They rhyme!'],
  'rhyme.oddyes': ['Yes! {word} does not rhyme.'],
  'rhyme.hint': ['Listen to the glowing one.'],
  'rhyme.done': ['What a rhyme time! Fine and dandy, sweet as candy!'],
  'beat.free': ['Tap squares to make a beat! Drums on top, claps below. Listen to it go round.'],
  'beat.done-when': ['When you like your beat, tap the green check!'],
  'beat.see': ['Copy the beat! Fill in the faint squares.'],
  'beat.hear': ['Listen to the beat, then build it! Tap the note to hear it again, and the green check when you are ready.'],
  'beat.repeat': ['Make the beat repeat! The second half should match the first half.'],
  'beat.notsee': ['That square is not in this beat. Look for the faint ones.'],
  'beat.notrepeat': ['Look at the first half. Does that square have a sound there?'],
  'beat.nothear': ['Not quite the same. Listen again!'],
  'beat.hint': ['The faint squares show where the beats are different.'],
  'beat.yay': ['That is the beat!', 'Groovy!', 'You got the rhythm!'],
  'beat.done': ['What a band! Thank you for the music!'],
  'snack.munch': ['Who is hungry? Tap an animal to give it a snack!'],
  'snack.float': ['Tap a snack, and it goes to the animal who loves it!'],
  'snack.match': ['Give each animal its favorite snack. Drag it to the one who eats it!'],
  'snack.who': ['Who eats the {food}? Tap the animal!'],
  'snack.count': ['Give the {animal} {n} {food}! Then ring the bell.'],
  'snack.yum': ['Yum! The {animal} loves {food}!', 'Munch munch! {food} for the {animal}!'],
  'snack.nothanks': ['No thank you! The {animal} eats {mine}. Who eats {food}?'],
  'snack.full': ['{n}! Thank you, says the {animal}!'],
  'snack.more': ['That is {have}. The {animal} wants {n}!'],
  'snack.toomany': ['That is too many! Only {n}, please. Here are the extras back.'],
  'snack.done': ['Everyone had a snack. Thank you!'],
  'night.all': ['It is bedtime! Tap everyone to say goodnight.'],
  'night.goodnight': ['Goodnight, {who}!', 'Sleep tight, {who}!', 'Night night, {who}!'],
  'night.named': ['Say goodnight to the {who}!'],
  'night.two': ['Say goodnight to the {a}, and then the {b}!'],
  'night.notthat': ['That is the {what}. Where is the {who}?'],
  'night.order': ['First the {a}, then the {b}.'],
  'night.done': ['Shh. Everyone is asleep. Goodnight!'],
  'pixel.copy': ['Make your picture look like the little one. Tap the squares!'],
  'pixel.copy2': ['Pick a color, then tap squares to copy the little picture.'],
  'pixel.mirror': ['Finish the picture! Make the right side match the left side, like a mirror.'],
  'pixel.clues': ['The numbers say how many squares to fill in a row, or down a column. Tap a square to fill it. What picture is hiding?'],
  'pixel.notthere': ['Not that square. Look at the little picture again.'],
  'pixel.notcolor': ['That square is {color}. Pick {color} first.'],
  'pixel.notmirror': ['Look across the middle line. Is that square filled on the other side?'],
  'pixel.notclue': ['That one stays empty. Count with the numbers again.'],
  'pixel.hint': ['Try the glowing square.'],
  'pixel.reveal': ['It is {name}!', 'Look, {name}!'],
  'pixel.done': ['What a gallery of pictures!'],
  'clock.hour': ["Turn the short hand to make it {time}. Then ring the bell!"],
  'clock.set': ['Make the clock say {time}. Turn the hands, then ring the bell!'],
  'clock.read': ['Look at the clock. What do we do at this time? Tap the picture.'],
  'clock.later': ['The clock says {time}. Make it say one hour later, then ring the bell!'],
  'clock.shows': ['The clock says {now}. We want {time}.'],
  'clock.later.wrong': ['That says {now}. One hour after {from}, the short hand moves on one number and the long hand ends up where it started.'],
  'clock.read.wrong': ['Not that one. Look where the short hand points, then the long hand.'],
  'clock.hint': ['Look at the yellow hands. Turn yours to match them.'],
  'clock.hint.read': ['The glowing picture matches the clock.'],
  'clock.itis': ['It is {time}: time for {event}!'],
  'clock.yay': ['Ding dong! Right on time!', 'Tick tock, you did it!'],
  'clock.done': ['The clock tower is right on time. Thank you!'],
  'grow.plant': ['Tap the soil to plant a seed. Watch it grow!'],
  'grow.water': ['Tap the soil to plant seeds. Then tap the cloud to make it rain!'],
  'grow.color': ['Plant a {color} flower! Tap the {color} seeds.'],
  'grow.count': ['Plant {n} seeds, then tap the cloud to make them grow.'],
  'grow.mix': ['Plant {n} {a} and {m} {b}. Then tap the cloud!'],
  'grow.notthat': ['Those are {color} seeds. Can you find the {want} ones?'],
  'grow.fewer': ['We planted {n}. We need {m}! Plant some more.'],
  'grow.more': ['We planted {n}. That is too many! We need {m}. Tap a seed to take it out.'],
  'grow.colors': ['Look at the colors again. Tap a seed to take it out.'],
  'grow.yay': ['Look how it grew!', 'Beautiful flowers!', 'Hooray, they bloomed!'],
  'grow.done': ['What a beautiful garden!'],
  'shop.pay': ['The {fruit} costs {n}. Tap coins onto the counter, then ring the bell!'],
  'shop.pair': ['A {a} for {n} and a {b} for {m}. How much for both? Pay, then ring the bell!'],
  'shop.change': ['You keep the stall! The {fruit} costs {n}, and they paid 10. Give them their change, then ring the bell.'],
  'shop.again': ['Thank you! Now buy another one, and pay a different way!'],
  'shop.short': ['Not enough yet. It costs {n}.'],
  'shop.over': ['That is too much! It costs {n}.'],
  'shop.change.short': ['They need more change. The price and the change together make 10.'],
  'shop.change.over': ['That is too much change! The price and the change together make 10.'],
  'shop.sameway': ['That is the same way as before! Try different coins.'],
  'shop.hint': ['Here is one way to make it.'],
  'shop.thanks': ['Thank you!', 'Here you go! Enjoy!', 'Thanks for shopping!'],
  'shop.done': ['The stall is all sold out. Thank you!'],
  'hop.find': ['Hop to {n}! Tap the lily pad with {n}.'],
  'hop.more': ['The frog is on {n}. Hop to one more!'],
  'hop.less': ['The frog is on {n}. Hop to one less!'],
  'hop.add': ['Start at {n}. Hop {k} more. Where will the frog land?'],
  'hop.back': ['Start at {n}. Hop back {k}. Where will the frog land?'],
  'hop.gap': ['How many hops from {n} to {m}? Tap a number card.'],
  'hop.wrong.find': ['That is {m}. Can you find {n}?'],
  'hop.wrong.more': ['One more is the very next pad, going up.'],
  'hop.wrong.less': ['One less is the pad just before, going back.'],
  'hop.wrong.count': ['Not quite. Count each hop from {n}.'],
  'hop.yay': ['Ribbit! Right on!', 'Splash! You got it!', 'Hoppy day!'],
  'hop.done': ['The frog hopped all the way home. Ribbit!'],
  'code.yesno': ['Tap stones to fill the slots, then turn the key. A green check means the right stone is in the right place. Gray means try another stone there.'],
  'code.yellow': ['Green means right stone, right place. Yellow means that stone is in the code, but in another slot. Gray means it is not in the code at all.'],
  'code.repeat': ['Careful, this door is tricky: a color can be used twice!'],
  'code.fill': ['Fill every slot first, then turn the key.'],
  'code.green': ['{g} green!'],
  'code.marks': ['{g} green and {y} yellow.'],
  'code.ignored': ['Look back at the marks: they already showed us the {color} stone does not go there.'],
  'code.hint': ['Here is an idea that fits every clue so far.'],
  'code.open': ['Click! The door opened!', 'You cracked the code!'],
  'code.done': ['Every door is open! What a code cracker!'],
  'slide.go': ['Tap the ice where the penguin should slide. It only stops when it bumps into something!'],
  'slide.two': ['Two fish this time! Slide past both of them.'],
  'slide.soft': ['Soft snow stops the penguin. Use it to stop in just the right place!'],
  'slide.stuck': ['Oh no, the penguin cannot reach the fish from here. Tap the round arrow to go back.'],
  'slide.hint': ['Follow the yellow arrow.'],
  'slide.yum': ['Yum!', 'A fish!', 'Gulp!'],
  'slide.done': ['A full and happy penguin! What clever sliding!'],
  'light.live': ['Tap the mirrors to turn them. Send the sunbeam to the sleepy flower!'],
  'light.plan': ['Turn the mirrors first. Then tap the sun to shine!'],
  'light.two': ['Wake up both flowers with one sunbeam. Turn the mirrors, then tap the sun!'],
  'light.color': ['The pink flower only wakes up in pink light. Shine through the pink glass, and wake the yellow flower first!'],
  'light.miss.edge': ['Oh! The light went off the edge. Look where it went, then turn a mirror.'],
  'light.miss.rock': ['Bonk! A rock blocked the light. Turn a mirror to go around it.'],
  'light.miss.color': ['The flower needs a different color of light. Which glass did the beam go through?'],
  'light.miss.sleeping': ['One flower woke up, but one is still sleeping. Can the light reach both?'],
  'light.hint': ['Try turning the mirror that is glowing.'],
  'light.yay': ['The flower woke up!', 'Sunshine!', 'Good morning, flower!'],
  'light.done': ['The whole garden is awake! What a bright idea!'],
  'around.find': ['Someone is hiding behind the tree! Turn the island to find them.'],
  'around.found': ['Peekaboo! It is the {who}!', 'There you are, {who}!'],
  'around.named': ['Where is the {who}? Turn the island to find the {who}!'],
  'around.notthat': ['That is the {what}! Where is the {who} hiding?'],
  'around.turn': ['Tap an arrow to turn the island and look behind the tree.'],
  'around.who': ['Who is hiding behind the tree? Tap their picture!'],
  'around.here.front': ["Not me! I'm in front of the tree."],
  'around.here.next': ["Not me! I'm next to the tree."],
  'around.place': ['Put the {who} {where} the tree!'],
  'around.two': ['Put the {a} {wa} the tree, and the {b} {wb} the tree!'],
  'around.hint.behind': ['Behind the tree is the far side, where the tree hides you.'],
  'around.hint.front': ['In front of the tree is this side, close to you.'],
  'around.hint.next': ['Next to the tree is at its side.'],
  'around.placed': ['The {who} is {where} the tree!'],
  'around.placed.behind': ['Now the {who} is hiding behind the tree!'],
  'around.otherside': ["Let's look from the other side!"],
  'around.now': ['Now the {who} is {where} the tree!'],
  'around.done': ['Everyone came out to play!'],
  'safari.snap': ['Tap an animal to take its picture!'],
  'safari.ask': ['Take a picture of {what}!'],
  'safari.thatis': ['That is {desc}!'],
  'safari.click': ['Click!', 'Say cheese!', 'Snap!'],
  'safari.done': ['What a photo album!', 'Look at all your photos!'],
  'mail.drop': ['Tap a mailbox to post a letter!'],
  'mail.color': ['This letter is for the {color} door!'],
  'mail.numeral': ['This letter is for number {n}!'],
  'mail.count': ['Count the dots on the letter. Which house is it for?'],
  'mail.number': ['Number {n}!'],
  'mail.thanks': ['Thank you!', 'A letter for me! Thank you!'],
  'mail.notme.color': ['Not for me! My door is {color}.'],
  'mail.notme.number': ["Not for me! I'm number {n}."],
  'mail.done': ['All the mail is delivered!'],
  'egg.tap': ['Tap a hen! Her egg rolls into the basket.'],
  'egg.catch': ['Slide the basket to catch the eggs!'],
  'egg.brown': ['Catch the brown eggs! Let the white eggs fall in the hay.'],
  'egg.route': ['Tap the gates so the egg rolls into the basket!'],
  'egg.sort': ['Brown eggs go in the basket. White eggs go to the nest. Tap the gates!'],
  'egg.white': ['Oops, that one is white! White eggs hatch in the hay.'],
  'egg.wrongway': ['Oops! It rolled the other way. Peep!'],
  'egg.predict': ['The gates are already set. Where will the egg land? Tap the hay, then watch it roll!'],
  'egg.predictwrong': ['It went another way! Follow the gates: each one sends the egg the way it points.'],
  'egg.done': ['All the eggs are safe!', 'What a lot of eggs!'],
  'helpers.tap': ['Tap the fruit! A little helper will carry it home.'],
  'helpers.send': ['Tap the fruit to send helpers. This one needs {n}!'],
  'helpers.count': ['This fruit needs {n} helpers. Send them, then blow the whistle!'],
  'helpers.more': ['{m} helpers are here. It needs {n}. How many more?'],
  'helpers.heavy': ['Too heavy! It needs {n} helpers.'],
  'helpers.extra': ['Too many! It only needs {n}.'],
  'helpers.groups': ['{n} fruits, and each one needs {m} helpers. Send them all, then blow the whistle!'],
  'helpers.groups.short': ['Too heavy! {m} helpers for each fruit. Count by {m}: {list}.'],
  'helpers.groups.extra': ['Too many! {m} helpers for each fruit. Count by {m}: {list}.'],
  'helpers.groups.total': ['{n} groups of {m} make {total}!'],
  'helpers.lift': ['Heave ho!', 'Lift!'],
  'helpers.done': ['All the fruit is home! Thank you, helpers!'],
  'sg.play': ['Tap the garden friends to hear them sing!'],
  'sg.highlow': ['Listen! Is it high like the bird, or low like the frog?'],
  'sg.fastslow': ['Listen! Is it fast like the bunny, or slow like the turtle?'],
  'sg.updown': ['Listen! Does the tune go up, or down?'],
  'sg.echo': ['Listen to the woodpecker. Then tap the drum the same way!'],
  'sg.again': ['Listen again!', 'Let us listen one more time.'],
  'sg.high': ['High!'],
  'sg.low': ['Low!'],
  'sg.fast': ['Fast!'],
  'sg.slow': ['Slow!'],
  'sg.up': ['Up!'],
  'sg.down': ['Down!'],
  'sg.echoyes': ['Tap tap! Just like the woodpecker!'],
  'sg.done': ['What a musical garden!'],
  'salon.play': ['Welcome to the salon! Pick a tool and brush the fluffy hair.'],
  'salon.want': ['Can you make my hair {look}, please?'],
  'salon.check': ['Let me look in the mirror!'],
  'salon.more': ['Almost! I want it {fix}.'],
  'salon.love': ['I love it!', 'So fluffy! Thank you!'],
  'salon.done': ['What a fancy look!', 'Looking good!'],
  'salon.tool.grow': ['Grow!'],
  'salon.tool.cut': ['Snip snip!'],
  'salon.tool.comb': ['Comb it straight!'],
  'salon.tool.curl': ['Curly!'],
  'peg.drop': ['Tap the top to drop a pearl!'],
  'peg.bloom': ['Drop pearls and make all the flowers bloom!'],
  'peg.color': ['Find the orange flowers! Make them bloom.'],
  'peg.number': ['Drag to aim, then let go. Hit {n}!'],
  'peg.order': ['Hit 1, then 2, then 3! Drag to aim, then let go.'],
  'peg.next': ['Now hit {n}!'],
  'peg.missed': ['So close! Try for {n} again.'],
  'peg.miss': ['Try a different spot!'],
  'peg.done': ['What a beautiful garden!'],
  'monster.play': ['Tap a letter monster to hear its sound!'],
  'monster.find': ['Find {letter}!', 'Where is {letter}?'],
  'monster.who': ['Who says {sound}?'],
  'monster.first': ['{word} starts with {sound}. Who says {sound}?'],
  'monster.build': ['Let us make {word}! {sounds}.'],
  'monster.family': ['Make {word}! {word} starts with {sound}.'],
  'monster.blend': ['{word}!'],
  'monster.iam': ["I'm {letter}! I say {sound}."],
  'monster.next': ['Next sound: {sound}.'],
  'monster.done': ['The word monsters say thank you!', 'Monster-ific!'],
  /** Letter sounds, written for the device voice. Recorded voices should say the real sound. */
  'sound.a': ['aah'],
  'sound.b': ['buh'],
  'sound.c': ['kuh'],
  'sound.d': ['duh'],
  'sound.e': ['eh'],
  'sound.f': ['fff'],
  'sound.g': ['guh'],
  'sound.h': ['huh'],
  'sound.i': ['ih'],
  'sound.j': ['juh'],
  'sound.k': ['kuh'],
  'sound.l': ['lll'],
  'sound.m': ['mmm'],
  'sound.n': ['nnn'],
  'sound.o': ['aw'],
  'sound.p': ['puh'],
  'sound.q': ['kwuh'],
  'sound.r': ['rrr'],
  'sound.s': ['sss'],
  'sound.t': ['tuh'],
  'sound.u': ['uh'],
  'sound.v': ['vvv'],
  'sound.w': ['wuh'],
  'sound.x': ['ks'],
  'sound.y': ['yuh'],
  'sound.z': ['zzz'],
  'launch.tap': ['Tap {pet} to bounce!'],
  'launch.pull': ['Pull {pet} back, and let go!'],
  'launch.star': ['Land on the star cloud!'],
  'launch.number': ['Land on {n}!'],
  'launch.farther': ['Now go farther!', 'Farther this time!'],
  'launch.nearer': ['Now not so far!', 'This time, not as far!'],
  'launch.short': ['A little farther! Pull more.'],
  'launch.long': ['Whoa, too far! Pull a little less.'],
  'launch.wee': ['Wheee!', 'Boing!', 'Up we go!'],
  'launch.done': ['What a flyer!', 'Great bouncing!'],
  'herd.tap': ['Tap the {animals} to send them home!'],
  'herd.shoo': ['Help the {animals} into their pen! Wiggle your finger behind them.'],
  'herd.sort': ['Pigs go in the mud. Bunnies go in the carrots!'],
  'herd.count': ['Put {n} {animals} in the pen, then ring the bell!'],
  'herd.sortcount': ['{a} pigs in the mud, and {b} bunnies in the carrots. Then ring the bell!'],
  'herd.short': ['We have {k}. We need {n}!'],
  'herd.wrongpen': ["Oops! That's the {pen} pen!"],
  'herd.extra': ["Oops, that's {count}! We need {n}."],
  'herd.done': ['Everyone is home!', 'All safe in their pens!'],
  'scoop.free': ['Make me a big ice cream!', 'Ice cream, please! Lots of scoops!'],
  'scoop.one': ['{a}, please!', 'One {a} scoop, please!'],
  'scoop.two': ['{a} and {b}, please!'],
  'scoop.twosame': ['Two {a} scoops, please!'],
  'scoop.count': ['{n} {a} scoops, please!'],
  'scoop.stack': ['{a} on the bottom, then {b}, then {c} on top!'],
  'scoop.notthat': ['No {color} for me! I want {want}.'],
  'scoop.notyet': ['Not {color} yet! Next is {want}.'],
  'scoop.enough': ["That's enough {color}!"],
  'scoop.yum': ['Yum! Thank you!', 'Mmm, delicious!', 'Thank you!'],
  'scoop.done': ['Everyone has ice cream!', 'What a busy shop!'],
  'parade.tap': ['Tap the grass to walk Mama Duck. Find her ducklings!'],
  'parade.walk': ['Help Mama Duck find her ducklings, then take them to the pond!'],
  'parade.count': ['Bring {n} ducklings to the pond!'],
  'parade.color': ['Find the {color} ducklings!'],
  'parade.colorcount': ['Bring {n} {color} ducklings to the pond!'],
  'parade.pattern': ['Make a pattern: {pattern}!'],
  'parade.home': ['Everyone is here! Take them to the pond!'],
  'parade.notme': ["Quack! I'm {color}. Find {want}!"],
  'parade.next': ['Next comes {want}!'],
  'parade.extra': ["Oops, that's {count}! We need {n}."],
  'parade.more': ['{k} in the pond. We need {n}!'],
  'parade.done': ['Everyone is home!', 'Splash! All home!'],
  'game.letter-trails': ['Letter Trails!'],
  'game.robot-path': ['Robot Path!'],
  'game.size-parade': ['Size Parade!'],
  'game.bug-builder': ['Bug Builder!'],
  'game.story-steps': ['Story Steps!'],
  'game.feelings-faces': ['Feelings faces!'],
  'game.monster-munch': ['Monster Munch!'],
  'game.song-maker': ['Song Maker!'],
  'game.puzzle-pals': ['Puzzle Pals!'],
  'game.weather-wardrobe': ['Weather Wardrobe!'],
  'game.sink-float': ['Sink or float!'],
  'size.pick': ['Tap the {size} friend!'],
  'size.line': ['Make a parade! Drag the {size} friend to the glowing spot, then find the next one.'],
  'size.wrong': ['Look at their sizes. Find the {size} friend still waiting.'],
  'size.hint': ['Look at the glowing friend!'],
  'size.next': ['Who comes next in our size parade?'],
  'size.done': ['What a lovely parade!'],
  'bug.guided': ['Decorate the bug! Drag each shape onto a matching spot.'],
  'bug.copy': ['Look at the little bug. Give the big bug the same shapes in the same places!'],
  'bug.mirror': ['Make matching wings! Put each shape across from its friend, like a mirror.'],
  'bug.wrong': ['Look closely at the shape, its color, and its place. Try another one!'],
  'bug.hint': ['Try the {color} {shape} in the glowing spot.'],
  'bug.done': ['Hello, beautiful bug!'],
  'story.start': ['{story}! Drag the picture that comes next into the glowing space. The music button tells the pictures we have placed.'],
  'story.wrong': ['What happened before this picture? Let us try another one.'],
  'story.hint': ['Try this glowing picture next!'],
  'story.step': ['{step}'],
  'pattern.start': ['Look at the train. What comes in the glowing space?'],
  'pattern.sound': ['Listen to the bells on the train. Which bell comes next? Tap a bell to listen, then tap the arrow.'],
  'pattern.wrong': ['Try another one. Look and listen to the pattern!'],
  'pattern.hint': ['This one! Can you find one just like it?'],
  'pattern.next': ['Yes! Now fill the next car!'],
  'memory.start': ['Turn over two cards to find a pair!'],
  'memory.number': ['Find the number and that many dots!'],
  'memory.letter': ['Find the big letter and its little letter!'],
  'memory.wrong': ['Let us remember those cards. Try another pair!'],
  'memory.hint': ['You have seen its friend. Look at the glowing card!'],
  'memory.pair': ['A pair!'],
  'trails.start': ['Follow the firefly to draw {letter}! Start at the glowing dot.'],
  'trails.stroke': ['Now follow this trail!'],
  'trails.wrong': ['Come back to the firefly. We can take our time.'],
  'trails.picture': ['{letter} is for {word}!'],
  'trails.word': ['Let us draw {word}!'],
  'robot.start': ['Help the robot reach the star! Tap arrows to make a path, then press play.'],
  'robot.counts': ['Tap an arrow again to go further: tap it four times for four steps! Then press play.'],
  'robot.loop': ['The purple loop button repeats your whole program. Make one part of the path, then loop it!'],
  'robot.wrong': ['A bump! Let us change our path and try again.'],
  'robot.hint': ['Follow the glowing arrow.'],
  'robot.clear': ['Let us try a new path.'],

  praise: ['Yay!', 'You did it!', 'Wow!', 'Great job, {name}!', 'Hooray!'],
  sticker: ['A sticker for you!', 'You got a sticker!'],
  again: ['Again?', 'Play again?'],

  'sleepy.warn': ["I'm getting sleepy. One more game!"],
  'sleepy.night': ['Goodnight, {name}. Sweet dreams!'],

  'bubble.free': ['Pop the bubbles!', 'Bubbles! Pop pop pop!'],
  'bubble.color': ['Pop the {color} bubbles!'],
  'bubble.wrong': ["That one's {wrong}. Find {color}!"],
  'bubble.count': ['Pop the numbers in order. Find one!'],
  'bubble.find': ['Find {n}!'],
  'bubble.rainbow': ['A rainbow bubble! Pop it!'],
  'bubble.bonds': ['Find two bubbles that make {n} together. Tap one, then its partner!'],
  'bubble.made': ['{a} and {b} make {n}!'],
  'bubble.notmade': ['{a} and {b} make {total}. We need {n}.'],

  'jelly.free': ['Tap the jellies to make music!'],
  'jelly.listen': ['Listen!', 'Listen to the jellies!'],
  'jelly.turn': ['Your turn!'],
  'jelly.oops': ['Hmm, listen again!'],
  'jelly.nice': ['Beautiful!', 'You got it!', 'Lovely music!'],

  'paint.start': ['Paint with your finger!'],
  'paint.done': ["I love it! Let's hang it up!", 'Beautiful painting!'],

  'peek.free': ['Who is hiding? Tap to find out!'],
  'peek.found': ['{word}! A {animal}!', "{word}! It's the {animal}!"],
  'peek.look': ['Look who is hiding!', 'Look!'],
  'peek.where': ['Where is the {animal}?', 'Can you find the {animal}?'],
  'peek.yes': ['You found the {animal}!', "There's the {animal}!"],
  'peek.notit': ["That's the {other}! Where is the {animal}?"],

  'duck.along': ['Tap a duck to help it swim!'],
  'duck.total': ['{n} ducks!', '{n} ducks swimming!'],
  'duck.make': ['Put {n} in the pond!'],
  'duck.made': ["That's {n}!", 'Yes, {n}!'],
  'duck.extra': ["Oops, that's {count}! We need {n}."],
  'duck.howmany': ['How many ducks?', 'How many ducks are swimming?'],
  'duck.countus': ["Let's count together!"],
  'duck.more': ['{a} ducks are swimming. {b} more come!'],
  'duck.away': ['{a} ducks are swimming. {b} swim away!'],
  'duck.now': ['How many now?'],
  'duck.ten': ['{a} ducks are swimming. How many more to make 10?'],
  'duck.counton': ["Let's count on from {a}, all the way to 10!"],
  'duck.tenmade': ['{a} and {b} make 10! A full pond!'],

  'shape.start': ['Put the shapes in the box!'],
  'shape.wrong': ["That's the {hole} hole. Try another one!"],
  'shape.done': ['All in! Yay!'],
  'shape.circle': ['Circle!'],
  'shape.square': ['Square!'],
  'shape.triangle': ['Triangle!'],
  'shape.star': ['Star!'],
  'shape.heart': ['Heart!'],
  'shape.hexagon': ['Hexagon!'],

  'garden.start': ['Put each one in the basket that matches!'],
  'garden.wrong': ['That one is {color}. Find the {color} basket!'],
  'garden.done': ['All sorted! What a garden!'],

  'bath.free': ['{pet} is muddy! Scrub scrub!'],
  'bath.part': ['Wash my {part}!', 'Now wash my {part}!'],
  'bath.notthat': ["Hee hee! That's my {touched}! Wash my {part}!"],
  'bath.two': ['Wash my {a} and my {b}!'],
  'bath.order': ['First wash my {a}, then my {b}!'],
  'bath.first': ['First my {a}! Then my {b}.'],
  'bath.clean': ['Squeaky clean!', 'All clean! Thank you!'],

  'paint.pots': ['Pick a color and paint!'],
  'paint.rainbow': ['Rainbow!'],
  'paint.ask': ['Paint the {thing} {color}!'],
  'paint.what': ['Paint the {thing}! What color is it?'],
  'paint.mix': ['Paint the {thing} {color}! Mix {a} and {b}.'],
  'paint.mixhow': ['Mix {a} and {b} to make {color}!'],
  'paint.pick': ['Find the {color} pot!'],
  'paint.wrong': ["That's {wrong}. The {thing} is {color}!"],
  'paint.finished': ['What a picture!', 'All colored in!'],

  'feel.play': ['Tap a bubble! How does {pet} feel?'],
  'feel.happy': ['Happy!', '{pet} feels happy!'],
  'feel.sad': ['Sad. Aww.', '{pet} feels sad.'],
  'feel.sleepy': ['Sleepy... yawn!', '{pet} feels sleepy.'],
  'feel.surprised': ['Surprised! Oh!', '{pet} feels surprised!'],
  'feel.hug': ['A big hug! That helps.', 'Hugs make it better.'],
  'feel.mirror': ['Find the face that looks like {pet}!'],
  'feel.find': ['Find the {feeling} face!'],
  'feel.that': ['That face looks {feeling}.'],
  'feel.need-sad': ['{pet} feels sad. What would help?'],
  'feel.need-sleepy': ['{pet} is so sleepy. What would help?'],
  'feel.need-hungry': ["{pet}'s tummy is rumbling! What would help?"],
  'feel.need-cold': ['Brr! {pet} is cold. What would help?'],
  'feel.not-that': ['Hmm, {pet} needs something else.'],
  'feel.helped': ['That helps! Thank you!', '{pet} feels better now.'],
  'feel.event-balloon': ['Oh no! The balloon floated away.'],
  'feel.event-present': ['Look! A present for {pet}!'],
  'feel.event-jack': ['Boing! Something jumped out!'],
  'feel.event-moon': ['The moon is up. It is very late.'],
  'feel.how': ['How does {pet} feel?'],
  'feel.friend': ['Find the friend who feels {feeling}!'],
  'feel.friend-that': ['That friend feels {feeling}.'],
  'feel.friend-yes': ['Yes! That friend feels {feeling}.'],
  'feel.hint': ['Try the glowing one!'],
  'feel.done': ['You know so many feelings!', 'What a kind friend you are!'],

  'munch.tap': ['The monster is hungry! Tap a cookie!'],
  'munch.count': ['Feed the monster! We will count every cookie.'],
  'munch.yum': ['Yum!', 'Num num num!', 'Crunchy!'],
  'munch.burp': ['Burp! Excuse me! Thank you!'],
  'munch.each': ['One cookie for each monster!'],
  'munch.had': ['I had mine! Who still needs a cookie?'],
  'munch.thanks': ['Thank you!'],
  'munch.everyone': ['Everyone has a cookie!'],
  'munch.want': ['Feed me {food}! Then ring the bell.'],
  'munch.need': ['I have {have}. I still need {food}!'],
  'munch.enough': ['That is enough {kind}! Here, you can have it back.'],
  'munch.right': ['Yes! {food}! Thank you!'],
  'munch.share': ['Share the cookies so every monster gets the same!'],
  'munch.unfair': ['Hmm, that is not fair yet. Some cookies come back!'],
  'munch.fair': ['Fair and square!'],
  'munch.each-how': ['How many cookies did each monster get?'],
  'munch.each-yes': ['Yes! {n} each!'],
  'munch.each-no': ['Let us count one monster together.'],
  'munch.leftover': ['Share the cookies so every monster gets the same. When no more can be shared fairly, ring the bell!'],
  'munch.more': ['It is fair so far, and there are enough cookies for everyone to have one more!'],
  'munch.left-how': ['And how many cookies are left over?'],
  'munch.left-yes': ['{n} left over! Those go to the pet. Yum!'],
  'munch.hint': ['Look at the glow!'],
  'munch.done': ['What a feast!'],

  'song.free': ['Tap the jellies to make a song! Listen to it go round and round.'],
  'song.copy': ['Tap the shadow jellies to make the song!'],
  'song.card': ['Make your song look just like the little card!'],
  'song.pattern': ['Look at the pattern. Keep the song going the same way!'],
  'song.listen': ['Listen to the tune. Then find each note, one beat at a time.'],
  'song.again': ['Listen again. Is it higher or lower?'],
  'song.wrong': ['Hmm, not that one. Try another jelly!'],
  'song.hint': ['Try the glowing jelly!'],
  'song.done': ['What a beautiful song!', 'You made music!'],

  'puzzle.ghost': ['Drag each piece onto the picture where it matches!'],
  'puzzle.start': ['Drag the pieces into the frame to make a picture!'],
  'puzzle.wrong': ['Hmm, that piece goes somewhere else. Look at its picture!'],
  'puzzle.hint': ['Try the glowing spot!'],
  'puzzle.done': ['You made {what}!'],

  'weather.play': ['Tap the sky to change the weather!'],
  'weather.sunny': ['Sunny! Hats and sunglasses on.'],
  'weather.rainy': ['Rainy! Pitter patter. Umbrella up!'],
  'weather.snowy': ['Snowy! Brr! Bundle up.'],
  'weather.pick': ['It is {weather} today! What should {pet} wear?'],
  'weather.all': ['It is {weather} today! Find everything {pet} needs.'],
  'weather.trip': ['We are going on a trip! First it will be {a}, then {b}. Pack what we need for both!'],
  'weather.wrong': ['{item} for {weather} days. Try another!'],
  'weather.yes': ['Good idea!', 'Just right!', 'Yes!'],
  'weather.ready': ['{pet} is ready to go out!', 'All set! Let us go!'],
  'weather.hint': ['Try the glowing one!'],

  'sink.drop': ['Tap something to drop it in the water! Splash!'],
  'sink.floats': ['It floats!', 'It floats on top!'],
  'sink.sinks': ['It sinks!', 'Down, down, it sinks!'],
  'sink.guess': ['Will the {thing} float or sink? Tap your guess!'],
  'sink.right': ['You guessed it!', 'Just like you thought!'],
  'sink.surprise': ['Surprise! Now we know.', 'What a surprise!'],
  'sink.sort': ['Put the floaters in the top basket and the sinkers in the bottom basket!'],
  'sink.oops': ['Let us test it in the water!'],
  'sink.hint': ['Look at the glowing basket!'],
  'sink.done': ['What a good scientist!'],

  'color.red': ['Red!'],
  'color.orange': ['Orange!'],
  'color.yellow': ['Yellow!'],
  'color.green': ['Green!'],
  'color.blue': ['Blue!'],
  'color.purple': ['Purple!'],
  'color.teal': ['Teal!'],
  'color.pink': ['Pink!'],
  'color.white': ['White!'],
  'color.brown': ['Brown!'],
  count: ['{n}!'],
} satisfies Record<string, string[]>;

export type LineId = keyof typeof SCRIPT;
