/**
 * Every line the game speaks, keyed by id. Arrays are variations picked at random.
 * `{name}` is the child's name; other `{words}` are filled in by the caller.
 * This is also the script for recording parents' voices later.
 */
export const SCRIPT = {
  'start.hi': ['Hi, {name}!', 'Hello, {name}!', 'Yay, {name} is here!'],
  'hub.pick': ['What should we play?', 'Pick a game!', "Let's play!"],
  'hub.again': ['What next?', 'Ooh, what now?'],
  'map.pick': ['Where shall we play, {pet}? Tap a place on our island!'],
  'map.birthday': ['Happy birthday, {pet}! We are growing up together. Let us walk up the island!'],
  'place.lap': ['Puddle Lagoon!'],
  'place.toddler': ['Daisy Meadow!'],
  'place.preschool': ['Bumpy Hills!'],
  'place.prek': ['Starry Peak!'],
  'place.more': ['Swipe to see more games!'],
  'hatch.tap': ['Someone is inside! Tap the egg!'],
  'hatch.color': ['Hello, little friend! Pick a color for your pet, then tap the green arrow.'],
  'hatch.name': ['What shall we call our friend? Tap a name to hear it, then tap the green arrow.'],
  'hatch.try-name': ['{pet}!'],
  'hatch.hello': ['Hello, {pet}! Let us explore our island!'],
  'stickers.place': ['Drag a sticker onto the picture! Put it back in the tray to move it away.'],
  'stickers.meadow': ['A meadow!'],
  'stickers.beach': ['The beach!'],
  'stickers.farm': ['A farm!'],
  'stickers.sea': ['Under the sea!'],
  'stickers.space': ['Outer space!'],
  'poke.pip': ['Hee hee!', 'That tickles!', 'Boop!', 'Hi!'],

  'game.bubble-pop': ['Bubbles!'],
  'game.jelly-drums': ['Jelly drums!'],
  'game.rainbow-fingers': ["Let's paint!"],
  'game.stickers': ['Your stickers!'],
  'game.peekaboo-barn': ['Peekaboo!'],
  'game.duck-pond': ['Duck pond!'],
  'game.shape-sorter': ['Shapes!'],
  'game.color-garden': ['The color garden!'],
  'game.splish-splash': ['Bath time!'],
  'game.pattern-train': ['Pattern Train!'],
  'game.memory-match': ['Memory Match!'],
  'game.letter-trails': ['Letter Trails!'],
  'game.robot-path': ['Robot Path!'],
  'game.size-parade': ['Size Parade!'],
  'game.bug-builder': ['Bug Builder!'],
  'game.story-steps': ['Story Steps!'],
  'game.feelings-faces': ['Feelings faces!'],
  'game.monster-munch': ['Monster Munch!'],
  'game.song-maker': ['Song Maker!'],
  'game.puzzle-pals': ['Puzzle Pals!'],
  'game.weather-wardrobe': ['Weather Wardrobe!'],
  'game.sink-float': ['Sink or float!'],
  'size.pick': ['Tap the {size} friend!'],
  'size.line': ['Make a parade! Drag the {size} friend to the glowing spot, then find the next one.'],
  'size.wrong': ['Look at their sizes. Find the {size} friend still waiting.'],
  'size.hint': ['Look at the glowing friend!'],
  'size.next': ['Who comes next in our size parade?'],
  'size.done': ['What a lovely parade!'],
  'bug.guided': ['Decorate the bug! Drag each shape onto a matching spot.'],
  'bug.copy': ['Look at the little bug. Give the big bug the same shapes in the same places!'],
  'bug.mirror': ['Make matching wings! Put each shape across from its friend, like a mirror.'],
  'bug.wrong': ['Look closely at the shape, its color, and its place. Try another one!'],
  'bug.hint': ['Try the {color} {shape} in the glowing spot.'],
  'bug.done': ['Hello, beautiful bug!'],
  'story.start': ['{story}! Drag the picture that comes next into the glowing space. The music button tells the pictures we have placed.'],
  'story.wrong': ['What happened before this picture? Let us try another one.'],
  'story.hint': ['Try this glowing picture next!'],
  'story.step': ['{step}'],
  'pattern.start': ['Look at the train. What comes in the glowing space?'],
  'pattern.sound': ['Listen to the bells on the train. Which bell comes next? Tap a bell to listen, then tap the arrow.'],
  'pattern.wrong': ['Try another one. Look and listen to the pattern!'],
  'pattern.hint': ['This one! Can you find one just like it?'],
  'pattern.next': ['Yes! Now fill the next car!'],
  'memory.start': ['Turn over two cards to find a pair!'],
  'memory.number': ['Find the number and that many dots!'],
  'memory.letter': ['Find the big letter and its little letter!'],
  'memory.wrong': ['Let us remember those cards. Try another pair!'],
  'memory.hint': ['You have seen its friend. Look at the glowing card!'],
  'memory.pair': ['A pair!'],
  'trails.start': ['Follow the firefly to draw {letter}! Start at the glowing dot.'],
  'trails.stroke': ['Now follow this trail!'],
  'trails.wrong': ['Come back to the firefly. We can take our time.'],
  'trails.picture': ['{letter} is for {word}!'],
  'trails.word': ['Let us draw {word}!'],
  'robot.start': ['Help the robot reach the star! Tap arrows to make a path, then press play.'],
  'robot.wrong': ['A bump! Let us change our path and try again.'],
  'robot.hint': ['Follow the glowing arrow.'],
  'robot.clear': ['Let us try a new path.'],

  praise: ['Yay!', 'You did it!', 'Wow!', 'Great job, {name}!', 'Hooray!'],
  sticker: ['A sticker for you!', 'You got a sticker!'],
  again: ['Again?', 'Play again?'],

  'sleepy.warn': ["I'm getting sleepy. One more game!"],
  'sleepy.night': ['Goodnight, {name}. Sweet dreams!'],

  'bubble.free': ['Pop the bubbles!', 'Bubbles! Pop pop pop!'],
  'bubble.color': ['Pop the {color} bubbles!'],
  'bubble.wrong': ["That one's {wrong}. Find {color}!"],
  'bubble.count': ['Pop the numbers in order. Find one!'],
  'bubble.find': ['Find {n}!'],
  'bubble.rainbow': ['A rainbow bubble! Pop it!'],

  'jelly.free': ['Tap the jellies to make music!'],
  'jelly.listen': ['Listen!', 'Listen to the jellies!'],
  'jelly.turn': ['Your turn!'],
  'jelly.oops': ['Hmm, listen again!'],
  'jelly.nice': ['Beautiful!', 'You got it!', 'Lovely music!'],

  'paint.start': ['Paint with your finger!'],
  'paint.done': ["I love it! Let's hang it up!", 'Beautiful painting!'],

  'peek.free': ['Who is hiding? Tap to find out!'],
  'peek.found': ['{word}! A {animal}!', "{word}! It's the {animal}!"],
  'peek.look': ['Look who is hiding!', 'Look!'],
  'peek.where': ['Where is the {animal}?', 'Can you find the {animal}?'],
  'peek.yes': ['You found the {animal}!', "There's the {animal}!"],
  'peek.notit': ["That's the {other}! Where is the {animal}?"],

  'duck.along': ['Tap a duck to help it swim!'],
  'duck.total': ['{n} ducks!', '{n} ducks swimming!'],
  'duck.make': ['Put {n} in the pond!'],
  'duck.made': ["That's {n}!", 'Yes, {n}!'],
  'duck.extra': ["Oops, that's {count}! We need {n}."],
  'duck.howmany': ['How many ducks?', 'How many ducks are swimming?'],
  'duck.countus': ["Let's count together!"],
  'duck.more': ['{a} ducks are swimming. {b} more come!'],
  'duck.away': ['{a} ducks are swimming. {b} swim away!'],
  'duck.now': ['How many now?'],

  'shape.start': ['Put the shapes in the box!'],
  'shape.wrong': ["That's the {hole} hole. Try another one!"],
  'shape.done': ['All in! Yay!'],
  'shape.circle': ['Circle!'],
  'shape.square': ['Square!'],
  'shape.triangle': ['Triangle!'],
  'shape.star': ['Star!'],
  'shape.heart': ['Heart!'],
  'shape.hexagon': ['Hexagon!'],

  'garden.start': ['Put each one in the basket that matches!'],
  'garden.wrong': ['That one is {color}. Find the {color} basket!'],
  'garden.done': ['All sorted! What a garden!'],

  'bath.free': ['{pet} is muddy! Scrub scrub!'],
  'bath.part': ['Wash my {part}!', 'Now wash my {part}!'],
  'bath.notthat': ["Hee hee! That's my {touched}! Wash my {part}!"],
  'bath.clean': ['Squeaky clean!', 'All clean! Thank you!'],

  'paint.pots': ['Pick a color and paint!'],
  'paint.rainbow': ['Rainbow!'],

  'feel.play': ['Tap a bubble! How does {pet} feel?'],
  'feel.happy': ['Happy!', '{pet} feels happy!'],
  'feel.sad': ['Sad. Aww.', '{pet} feels sad.'],
  'feel.sleepy': ['Sleepy... yawn!', '{pet} feels sleepy.'],
  'feel.surprised': ['Surprised! Oh!', '{pet} feels surprised!'],
  'feel.hug': ['A big hug! That helps.', 'Hugs make it better.'],
  'feel.mirror': ['Find the face that looks like {pet}!'],
  'feel.find': ['Find the {feeling} face!'],
  'feel.that': ['That face looks {feeling}.'],
  'feel.need-sad': ['{pet} feels sad. What would help?'],
  'feel.need-sleepy': ['{pet} is so sleepy. What would help?'],
  'feel.need-hungry': ["{pet}'s tummy is rumbling! What would help?"],
  'feel.need-cold': ['Brr! {pet} is cold. What would help?'],
  'feel.not-that': ['Hmm, {pet} needs something else.'],
  'feel.helped': ['That helps! Thank you!', '{pet} feels better now.'],
  'feel.event-balloon': ['Oh no! The balloon floated away.'],
  'feel.event-present': ['Look! A present for {pet}!'],
  'feel.event-jack': ['Boing! Something jumped out!'],
  'feel.event-moon': ['The moon is up. It is very late.'],
  'feel.how': ['How does {pet} feel?'],
  'feel.friend': ['Find the friend who feels {feeling}!'],
  'feel.friend-that': ['That friend feels {feeling}.'],
  'feel.friend-yes': ['Yes! That friend feels {feeling}.'],
  'feel.hint': ['Try the glowing one!'],
  'feel.done': ['You know so many feelings!', 'What a kind friend you are!'],

  'munch.tap': ['The monster is hungry! Tap a cookie!'],
  'munch.count': ['Feed the monster! We will count every cookie.'],
  'munch.yum': ['Yum!', 'Num num num!', 'Crunchy!'],
  'munch.burp': ['Burp! Excuse me! Thank you!'],
  'munch.each': ['One cookie for each monster!'],
  'munch.had': ['I had mine! Who still needs a cookie?'],
  'munch.thanks': ['Thank you!'],
  'munch.everyone': ['Everyone has a cookie!'],
  'munch.want': ['Feed me {food}! Then ring the bell.'],
  'munch.need': ['I have {have}. I still need {food}!'],
  'munch.enough': ['That is enough {kind}! Here, you can have it back.'],
  'munch.right': ['Yes! {food}! Thank you!'],
  'munch.share': ['Share the cookies so every monster gets the same!'],
  'munch.unfair': ['Hmm, that is not fair yet. Some cookies come back!'],
  'munch.fair': ['Fair and square!'],
  'munch.each-how': ['How many cookies did each monster get?'],
  'munch.each-yes': ['Yes! {n} each!'],
  'munch.each-no': ['Let us count one monster together.'],
  'munch.hint': ['Look at the glow!'],
  'munch.done': ['What a feast!'],

  'song.free': ['Tap the jellies to make a song! Listen to it go round and round.'],
  'song.copy': ['Tap the shadow jellies to make the song!'],
  'song.card': ['Make your song look just like the little card!'],
  'song.pattern': ['Look at the pattern. Keep the song going the same way!'],
  'song.listen': ['Listen to the tune. Then find each note, one beat at a time.'],
  'song.again': ['Listen again. Is it higher or lower?'],
  'song.wrong': ['Hmm, not that one. Try another jelly!'],
  'song.hint': ['Try the glowing jelly!'],
  'song.done': ['What a beautiful song!', 'You made music!'],

  'puzzle.ghost': ['Drag each piece onto the picture where it matches!'],
  'puzzle.start': ['Drag the pieces into the frame to make a picture!'],
  'puzzle.wrong': ['Hmm, that piece goes somewhere else. Look at its picture!'],
  'puzzle.hint': ['Try the glowing spot!'],
  'puzzle.done': ['You made {what}!'],

  'weather.play': ['Tap the sky to change the weather!'],
  'weather.sunny': ['Sunny! Hats and sunglasses on.'],
  'weather.rainy': ['Rainy! Pitter patter. Umbrella up!'],
  'weather.snowy': ['Snowy! Brr! Bundle up.'],
  'weather.pick': ['It is {weather} today! What should {pet} wear?'],
  'weather.all': ['It is {weather} today! Find everything {pet} needs.'],
  'weather.trip': ['We are going on a trip! First it will be {a}, then {b}. Pack what we need for both!'],
  'weather.wrong': ['{item} for {weather} days. Try another!'],
  'weather.yes': ['Good idea!', 'Just right!', 'Yes!'],
  'weather.ready': ['{pet} is ready to go out!', 'All set! Let us go!'],
  'weather.hint': ['Try the glowing one!'],

  'sink.drop': ['Tap something to drop it in the water! Splash!'],
  'sink.floats': ['It floats!', 'It floats on top!'],
  'sink.sinks': ['It sinks!', 'Down, down, it sinks!'],
  'sink.guess': ['Will the {thing} float or sink? Tap your guess!'],
  'sink.right': ['You guessed it!', 'Just like you thought!'],
  'sink.surprise': ['Surprise! Now we know.', 'What a surprise!'],
  'sink.sort': ['Put the floaters in the top basket and the sinkers in the bottom basket!'],
  'sink.oops': ['Let us test it in the water!'],
  'sink.hint': ['Look at the glowing basket!'],
  'sink.done': ['What a good scientist!'],

  'color.red': ['Red!'],
  'color.orange': ['Orange!'],
  'color.yellow': ['Yellow!'],
  'color.green': ['Green!'],
  'color.blue': ['Blue!'],
  'color.purple': ['Purple!'],
  'color.teal': ['Teal!'],
  'color.pink': ['Pink!'],
  'color.white': ['White!'],
  'color.brown': ['Brown!'],
  count: ['{n}!'],
} satisfies Record<string, string[]>;

export type LineId = keyof typeof SCRIPT;
